package gov.nist.toolkit.common.adt;

import java.sql.SQLException;

import junit.framework.TestCase;


public class AdtRecordBeanTest extends TestCase {

	public void test_allocate()  {
		allocate();
	}

	public String allocate()  {
		try {
			AdtRecordBean bean = new AdtRecordBean();
			bean.setPatientIdAutoGenerated("&1.3.6.1.4.1.21367.2005.3.7&ISO");
			bean.setSaveToDatabase(null);
			return bean.getPatientId();
		}
		catch (ClassNotFoundException e) {
			fail("ClassNotFoundException " + e.getMessage());
		}
		catch (SQLException e) {
			fail("SQLException " + e.getMessage());
		}
		return null;
	}



	public void test_verify() {
		Verify v = new Verify();
		try {
			v.isValid(allocate());
		}
		catch (ClassNotFoundException e) {
			fail("ClassNotFoundException " + e.getMessage());
		}
		catch (SQLException e) {
			fail("SQLException " + e.getMessage());
		}
	}

}
