package gov.nist.toolkit.fhir.transaction

import gov.nist.toolkit.fhir.context.ToolkitFhirContext
import gov.nist.toolkit.fhir.server.utility.FhirId
import org.hl7.fhir.instance.model.api.IBaseResource
import spock.lang.Specification

class ParseTest extends Specification {

    def 'work' () {
        when:
        def docRef = parseResource(dr)
        FhirId id = new FhirId(docRef)

        then:
        id.id == '29976'

    }

    IBaseResource parseResource(def text) {
        ToolkitFhirContext.get().newXmlParser().parseResource(text)
    }

    def dr = '''
         <DocumentReference
               xmlns="http://hl7.org/fhir">
            <id
                  value="29976"
                  xmlns="http://hl7.org/fhir"/>
            <meta
                  xmlns="http://hl7.org/fhir">
               <versionId
                     value="1"
                     xmlns="http://hl7.org/fhir"/>
               <lastUpdated
                     value="2019-04-04T10:37:00.003+02:00"
                     xmlns="http://hl7.org/fhir"/>
            </meta>
            <text
                  xmlns="http://hl7.org/fhir">
               <status
                     value="generated"
                     xmlns="http://hl7.org/fhir"/>
            </text>
            <contained
                  xmlns="http://hl7.org/fhir">
               <Practitioner
                     xmlns="http://hl7.org/fhir">
                  <id
                        value="a3"
                        xmlns="http://hl7.org/fhir"/>
                  <name
                        xmlns="http://hl7.org/fhir">
                     <use
                           value="usual"
                           xmlns="http://hl7.org/fhir"/>
                     <family
                           value="Smitty"
                           xmlns="http://hl7.org/fhir"/>
                     <given
                           value="Gerald"
                           xmlns="http://hl7.org/fhir"/>
                  </name>
               </Practitioner>
            </contained>
            <contained
                  xmlns="http://hl7.org/fhir">
               <Practitioner
                     xmlns="http://hl7.org/fhir">
                  <id
                        value="a4"
                        xmlns="http://hl7.org/fhir"/>
                  <name
                        xmlns="http://hl7.org/fhir">
                     <use
                           value="usual"
                           xmlns="http://hl7.org/fhir"/>
                     <family
                           value="Dopplemeyer"
                           xmlns="http://hl7.org/fhir"/>
                     <given
                           value="Sherry"
                           xmlns="http://hl7.org/fhir"/>
                  </name>
               </Practitioner>
            </contained>
            <contained
                  xmlns="http://hl7.org/fhir">
               <Patient
                     xmlns="http://hl7.org/fhir">
                  <id
                        value="a2"
                        xmlns="http://hl7.org/fhir"/>
                  <identifier
                        xmlns="http://hl7.org/fhir">
                     <use
                           value="usual"
                           xmlns="http://hl7.org/fhir"/>
                     <type
                           xmlns="http://hl7.org/fhir">
                        <coding
                              xmlns="http://hl7.org/fhir">
                           <system
                                 value="urn:ietf:rfc:3986"
                                 xmlns="http://hl7.org/fhir"/>
                           <code
                                 value="urn:ihe:iti:xds:2013:accession"
                                 xmlns="http://hl7.org/fhir"/>
                        </coding>
                     </type>
                     <system
                           value="urn:oid:1.2.3.4.5.6"
                           xmlns="http://hl7.org/fhir"/>
                     <value
                           value="MRN"
                           xmlns="http://hl7.org/fhir"/>
                  </identifier>
                  <name
                        xmlns="http://hl7.org/fhir">
                     <use
                           value="usual"
                           xmlns="http://hl7.org/fhir"/>
                     <text
                           value="DOE, John"
                           xmlns="http://hl7.org/fhir"/>
                     <family
                           value="Doe"
                           xmlns="http://hl7.org/fhir"/>
                     <given
                           value="John"
                           xmlns="http://hl7.org/fhir"/>
                  </name>
                  <birthDate
                        value="1956-05-27"
                        xmlns="http://hl7.org/fhir"/>
               </Patient>
            </contained>
            <masterIdentifier
                  xmlns="http://hl7.org/fhir">
               <system
                     value="http://example.org/documents"
                     xmlns="http://hl7.org/fhir"/>
               <value
                     value="urn:oid:1.2.42.20190403160849.128"
                     xmlns="http://hl7.org/fhir"/>
            </masterIdentifier>
            <status
                  value="current"
                  xmlns="http://hl7.org/fhir"/>
            <type
                  xmlns="http://hl7.org/fhir">
               <coding
                     xmlns="http://hl7.org/fhir">
                  <system
                        value="http://loinc.org"
                        xmlns="http://hl7.org/fhir"/>
                  <code
                        value="34133-9"
                        xmlns="http://hl7.org/fhir"/>
                  <display
                        value="Summary of Episode Note"
                        xmlns="http://hl7.org/fhir"/>
               </coding>
            </type>
            <class
                  xmlns="http://hl7.org/fhir">
               <coding
                     xmlns="http://hl7.org/fhir">
                  <system
                        value="urn:oid:1.3.6.1.4.1.19376.1.2.6.1"
                        xmlns="http://hl7.org/fhir"/>
                  <code
                        value="REPORTS"
                        xmlns="http://hl7.org/fhir"/>
                  <display
                        value="Reports"
                        xmlns="http://hl7.org/fhir"/>
               </coding>
            </class>
            <subject
                  xmlns="http://hl7.org/fhir">
               <reference
                     value="http://avolpe:8080/xdstools7.2.6/fsim/default__fhir_support/fhir/Patient/99ef14a6-3fbb-4b60-99bf-ba829b60e2ae"
                     xmlns="http://hl7.org/fhir"/>
            </subject>
            <created
                  value="2005-12-24"
                  xmlns="http://hl7.org/fhir"/>
            <indexed
                  value="2013-07-01T23:11:33+10:00"
                  xmlns="http://hl7.org/fhir"/>
            <author
                  xmlns="http://hl7.org/fhir">
               <reference
                     value="#a3"
                     xmlns="http://hl7.org/fhir"/>
            </author>
            <author
                  xmlns="http://hl7.org/fhir">
               <reference
                     value="#a4"
                     xmlns="http://hl7.org/fhir"/>
            </author>
            <description
                  value="Physical"
                  xmlns="http://hl7.org/fhir"/>
            <securityLabel
                  xmlns="http://hl7.org/fhir">
               <coding
                     xmlns="http://hl7.org/fhir">
                  <system
                        value="http://hl7.org/fhir/v3/Confidentiality"
                        xmlns="http://hl7.org/fhir"/>
                  <code
                        value="N"
                        xmlns="http://hl7.org/fhir"/>
                  <display
                        value="normal"
                        xmlns="http://hl7.org/fhir"/>
               </coding>
            </securityLabel>
            <content
                  xmlns="http://hl7.org/fhir">
               <attachment
                     xmlns="http://hl7.org/fhir">
                  <contentType
                        value="text/plain"
                        xmlns="http://hl7.org/fhir"/>
                  <language
                        value="en-us"
                        xmlns="http://hl7.org/fhir"/>
                  <url
                        value="textfile"
                        xmlns="http://hl7.org/fhir"/>
               </attachment>
               <format
                     xmlns="http://hl7.org/fhir">
                  <system
                        value="urn:oid:1.3.6.1.4.1.19376.1.2.3"
                        xmlns="http://hl7.org/fhir"/>
                  <code
                        value="urn:ihe:pcc:handp:2008"
                        xmlns="http://hl7.org/fhir"/>
               </format>
            </content>
            <context
                  xmlns="http://hl7.org/fhir">
               <period
                     xmlns="http://hl7.org/fhir">
                  <start
                        value="2004-12-23T08:00:00+10:00"
                        xmlns="http://hl7.org/fhir"/>
                  <end
                        value="2004-12-23T08:01:00+10:00"
                        xmlns="http://hl7.org/fhir"/>
               </period>
               <facilityType
                     xmlns="http://hl7.org/fhir">
                  <coding
                        xmlns="http://hl7.org/fhir">
                     <system
                           value="http://snomed.info/sct"
                           xmlns="http://hl7.org/fhir"/>
                     <code
                           value="225728007"
                           xmlns="http://hl7.org/fhir"/>
                     <display
                           value="Private physicians group office"
                           xmlns="http://hl7.org/fhir"/>
                  </coding>
               </facilityType>
               <practiceSetting
                     xmlns="http://hl7.org/fhir">
                  <coding
                        xmlns="http://hl7.org/fhir">
                     <system
                           value="http://connectathon.ihe"
                           xmlns="http://hl7.org/fhir"/>
                     <code
                           value="Practice-A"
                           xmlns="http://hl7.org/fhir"/>
                     <display
                           value="Radiology"
                           xmlns="http://hl7.org/fhir"/>
                  </coding>
               </practiceSetting>
               <sourcePatientInfo
                     xmlns="http://hl7.org/fhir">
                  <reference
                        value="#a2"
                        xmlns="http://hl7.org/fhir"/>
               </sourcePatientInfo>
            </context>
         </DocumentReference>'''
}
