#!/bin/sh

#-genkeypair  [-v] [-protected]
#	     [-alias <alias>]
#	     [-keyalg <keyalg>] [-keysize <keysize>]
#	     [-sigalg <sigalg>] [-dname <dname>]
#	     [-validity <valDays>] [-keypass <keypass>]
#	     [-keystore <keystore>] [-storepass <storepass>]
#	     [-storetype <storetype>] [-providername <name>]
#	     [-providerclass <provider_class_name> [-providerarg <arg>]] ...
#	     [-providerpath <pathlist>]


keytool -genkeypair -keyalg RSA -storepass changeit  -keystore ./keystore.jks 
