package gov.nist.toolkit.xdstools2.client;

/**
 * Created by skb1 on 10/21/2016.
 */
public enum GazelleXuaUsername {
    valid,
    notyetvalid,
    expired,
    unsigned,
    invalidsignature,
    missingkeyinfo,
    missingkeyvalue,
    missingrsakeyvalue,
    missingrsakeymodulus,
    missingrsakeyexponent,
    invalidversion,
    missingversion,
    invalidid,
    missingid,
    missingsubjectconfirmation,
    missingsubjectconfirmationmethod,
    missingsubject,
    missingsubjectnameid,
    missingissuer,
    missingissuerformat,
    invalidissueremailformat,
    invalidissuerx509format,
    invalidissuerwindowsdomainformat,
    missingissueinstant,
    invalidissueinstant,
    invalidrsapublickeymodulus,
    invalidrsapublickeyexponent,
    invalidsubjectnameidformat,
    invalidx509certificate,
    lateissueinstant,
    missingsubjectconfdata,
    missingsubjectconfirmationkeyinfo,
    missingsubjectconfrsapublickeyexponent,
    invalidsubjectconfrsapublickeymodulus,
    invalidsubjectconfrsapublickeyexponent,
    unknownaudience,
    invalidauthncontext,
    secondauthncontext,
    secondrole,
    secondpurposeofuse,
    withauthzconsent,

    secondpurposeofuseDOTCOVERAGE,
    secondpurposeofuseDOTOPERATIONS,
    secondpurposeofuseDOTPAYMENT,
    secondpurposeofuseDOTPUBLICHEALTH,
    secondpurposeofuseDOTREQUEST,
    secondpurposeofuseDOTTREATMENT,
    secondpurposeofuseDOTLEGACYTREATMENT,
    secondpurposeofuseDOTREASSURANCE,
    secondpurposeofuseDOTTREATMENTOID,
    secondpurposeofuseDOTCOVERAGEOID,
    secondpurposeofuseDOTOPERATIONSOID,
    secondpurposeofuseDOTPAYMENTOID,
    secondpurposeofuseDOTPUBLICHEALTHOID,
    secondpurposeofuseDOTREQUESTOID


}
